# Define base paths
patch_size: 256
step_size: 256
patch_level: 0
slide_ext: ".tif"
model: "virchow_v2"

# Fully expanded paths
raw_slides_dir: "/tank/WSI_data/Ovarian_WSIs/Bevacizumab_response_cohort/slides"
patch_save_dir: "/tank/WSI_data/Ovarian_WSIs/Bevacizumab_response_cohort/CLAM/20X/patches"
csv_path: "/tank/WSI_data/Ovarian_WSIs/Bevacizumab_response_cohort/CLAM/20X/patches/process_list_autogen.csv"
feat_dir: "/tank/WSI_data/Ovarian_WSIs/Bevacizumab_response_cohort/CLAM/20X/virchow_v2"

batch_size: 512
max_patches: 3000000000
cuda_devices_patch: "0,1,2"
cuda_devices_embed: "0,1,2"
preset: "CLAM/presets/bwh_resection.csv"
