# Define base paths

microns_per_patch_edge: 256 

patch_level: 0
slide_ext: ".svs"
model: "uni_v1"

# Fully expanded paths
raw_slides_dir: "/tank/WSI_data/Ovarian_WSIs/MSK-IMPACT/hne/mskcc"
patch_save_dir: "/tank/WSI_data/Ovarian_WSIs/MSK-IMPACT/CLAM/256ppp/patches"
csv_path: "/tank/WSI_data/Ovarian_WSIs/MSK-IMPACT/CLAM/256ppp/patches/process_list_autogen.csv"
feat_dir: "/tank/WSI_data/Ovarian_WSIs/MSK-IMPACT/CLAM/256ppp/uni_v1"

batch_size: 512
max_patches: 3000000000
cuda_devices_patch: "0,2"
cuda_devices_embed: "0,2"
preset: "CLAM/presets/bwh_biopsy.csv"
