microns_per_patch_edge: 256 

patch_level: 0
slide_ext: ".mrxs"
model: "conch_v1_5"

# Fully expanded paths
raw_slides_dir: "/nemo/project/proj-tracerx-lung/tctProjects/kilimo/data/Karoly/slides/ORACLE_1"
patch_save_dir: "/nemo/project/proj-tracerx-lung/tctProjects/kilimo/data/Karoly/CLAM/10X/patches"
csv_path: "/nemo/project/proj-tracerx-lung/tctProjects/kilimo/data/Karoly/CLAM/10X/patches/process_list_autogen.csv"
feat_dir: "/nemo/project/proj-tracerx-lung/tctProjects/kilimo/data/Karoly/CLAM/10X/patches/conch_v1_5"
batch_size: 512
max_patches: 3000000000
cuda_devices_patch: "0"
cuda_devices_embed: "0"
preset: "CLAM/presets/bwh_biopsy.csv"
