microns_per_patch_edge: 128 

patch_level: 0
slide_ext: ".mrxs"
model: "uni_v2"

# Fully expanded paths
raw_slides_dir: "/tank/WSI_data/lung/Zoltan-lung_spatial/figshare_collection_downloads"
patch_save_dir: "/tank/WSI_data/lung/Zoltan-lung_spatial/CLAM/20X/patches"
csv_path: "/tank/WSI_data/lung/Zoltan-lung_spatial/CLAM/20X/patches/process_list_autogen_no_zip.csv"
feat_dir: "/tank/WSI_data/lung/Zoltan-lung_spatial/CLAM/20X/uni_v2"
batch_size: 512
max_patches: 3000000000
cuda_devices_patch: "0"
cuda_devices_embed: "0"
preset: "CLAM/presets/bwh_biopsy.csv"
