cuda_devices_patch: "0"
cuda_devices_embed: "0,1,2"
patch_size: 256
step_size: 256
preset: "CLAM/presets/bwh_biopsy.csv"
patch_level: 0
max_patches: 3000000000
batch_size: 512
model: "virchow_v2"
raw_slides_dir: "/tank/WSI_data/TCGA_WSI_organized/TCGA-PRAD/FFPE_slides"
patch_save_dir: "/tank/WSI_data/TCGA_WSI_organized/TCGA-PRAD/FFPE_slides/20X_NADT/patches"
csv_path: "/tank/WSI_data/TCGA_WSI_organized/TCGA-PRAD/FFPE_slides/20X_NADT/patches/process_list_autogen.csv"
slide_ext: ".svs"
feat_dir: "/tank/WSI_data/TCGA_WSI_organized/TCGA-PRAD/FFPE_slides/20X_NADT/virchow_v2"