# Define base paths

microns_per_patch_edge: 128 

patch_level: 0
slide_ext: ".mrxs"
model: "uni_v2"

# Marking removal configuration - by default disabled
# When enabled, all colors are removed by default unless specifically disabled
remove_markings: true

# Optional: disable specific colors when remove_markings is true
# Uncomment and set to true to disable specific color removal
# disable_red_removal: false
# disable_blue_removal: false
# disable_green_removal: false
disable_off_white_removal: true
# disable_black_removal: false

# Advanced: Custom color ranges (optional)
# If you need to customize the HSV color ranges for detection
# marking_colors:
#   red:
#     enabled: true
#     lower1: [0, 100, 80]
#     upper1: [10, 255, 255]
#     lower2: [170, 100, 80]
#     upper2: [180, 255, 255]
#   blue:
#     enabled: true
#     lower: [100, 100, 80]
#     upper: [130, 255, 255]
#   green:
#     enabled: true
#     lower: [35, 5, 5]
#     upper: [90, 255, 255]
#   off_white:
#     enabled: true
#     lower: [0, 0, 200]
#     upper: [179, 30, 255]
#   black:
#     enabled: true
#     lower: [0, 0, 0]
#     upper: [179, 255, 80]

# Fully expanded paths
raw_slides_dir: "/tank/WSI_data/Ovarian_WSIs/OOI/slides"
patch_save_dir: "/tank/WSI_data/Ovarian_WSIs/OOI/CLAM/20X/patches"
csv_path: "/tank/WSI_data/Ovarian_WSIs/OOI/CLAM/20X/patches/process_list_autogen.csv"
feat_dir: "/tank/WSI_data/Ovarian_WSIs/OOI/CLAM/20X/uni_v2"

batch_size: 512
max_patches: 3000000000
cuda_devices_patch: "0,2"
cuda_devices_embed: "0,2"
preset: "CLAM/presets/bwh_biopsy.csv"