# Example configuration with marking removal enabled
# This config shows how to enable marking removal functionality

microns_per_patch_edge: 128 

patch_level: 0
slide_ext: ".mrxs"
model: "uni_v2"

# Enable marking removal - all colors will be removed by default
remove_markings: true

# Optional: disable specific colors if you don't want them removed
# For example, if you want to keep green markings but remove everything else:
# disable_green_removal: true

# Fully expanded paths
raw_slides_dir: "/tank/WSI_data/Ovarian_WSIs/OOI/slides"
patch_save_dir: "/tank/WSI_data/Ovarian_WSIs/OOI/CLAM/20X/patches"
csv_path: "/tank/WSI_data/Ovarian_WSIs/OOI/CLAM/20X/patches/process_list_autogen.csv"
feat_dir: "/tank/WSI_data/Ovarian_WSIs/OOI/CLAM/20X/uni_v2"

batch_size: 512
max_patches: 3000000000
cuda_devices_patch: "0,2"
cuda_devices_embed: "0,2"
preset: "CLAM/presets/bwh_biopsy.csv" 